1.Importar librerias

In [1]:
import pandas as pd
import numpy as np

2. Cargar el dataset

In [6]:
ruta= ("../data/raw/dataset_7variables_2000_2022.csv")
df=pd.read_csv(ruta)

3. Exploramos datos

In [7]:
df.describe().T.round(1)

,count,mean,std,min,25%,50%,75%,max
year,4244.0,2011.1,6.6,2000.0,2005.0,2011.0,2017.0,2.022000e+03
population,4244.0,76179062.5,539694002.1,9566.0,1921557.8,7382109.5,26096305.8,8.021407e+09
births,4244.0,1495146.1,10502980.1,197.0,31771.8,138645.0,615917.0,1.460549e+08
deaths,4244.0,599805.0,4226299.9,66.0,14227.8,57920.0,201302.0,6.972810e+07
child_deaths_under_5,4244.0,77675.4,564574.1,0.0,323.0,2857.5,23048.0,1.018010e+07
percentage_health,4244.0,6.2,2.8,1.2,4.1,5.7,7.9,2.450000e+01
gdp,4244.0,21716.5,23529.0,712.0,4826.0,13202.0,30472.1,1.490251e+05
life_expectancy,4244.0,70.0,8.7,14.7,64.5,71.4,76.5,8.570000e+01

In [8]:
df.columns.to_list()

['entity',
 'year',
 'population',
 'births',
 'deaths',
 'child_deaths_under_5',
 'percentage_health',
 'gdp',
 'life_expectancy']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4244 entries, 0 to 4243
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   entity                4244 non-null   str
 1   year                  4244 non-null   int64
 2   population            4244 non-null   float64
 3   births                4244 non-null   float64
 4   deaths                4244 non-null   float64
 5   child_deaths_under_5  4244 non-null   int64
 6   percentage_health     4244 non-null   float64
 7   gdp                   4244 non-null   float64
 8   life_expectancy       4244 non-null   float64
dtypes: float64(6), int64(2), str(1)
memory usage: 298.5 KB

In [12]:
df.isnull().sum() #me da la cantidad de nulos que tengo para cada uno

entity                  0
year                    0
population              0
births                  0
deaths                  0
child_deaths_under_5    0
percentage_health       0
gdp                     0
life_expectancy         0
dtype: int64

4. Seleccionar variables

In [13]:
variables_numericas = ["population",
                       "births",
                       "deaths",
                       "child_deaths_under_5",
                       "percentage_health",
                       "gdp",                   
                       "life_expectancy"
]
df_vn = df[variables_numericas].copy()

df_vn.head(3)

,population,births,deaths,child_deaths_under_5,percentage_health,gdp,life_expectancy
0,21378123.0,1015202.0,239161.0,123215,9.443391,1774.3087,56.2251
1,22733053.0,1069727.0,243573.0,123894,8.941258,1815.9282,57.1713
2,23560656.0,1095372.0,244435.0,122315,9.808474,1776.9182,57.8098

5. Exploramos las combinaciones

In [15]:
from itertools import combinations
from math import comb

#Calcular el número de combinaciones
n= len(variables_numericas)
total_combinaciones = comb(n,2)

print(f"Número de combinaciones: {total_combinaciones}")

Número de combinaciones: 21

In [17]:
# inicializamos el arreglo para guardar los resultados
resultados = []

for variable_x, variable_y in combinations(variables_numericas, 2):
    # se calcular r mediante la funcion corr de pandas
    r = df_vn[variable_x].corr(df_vn[variable_y], method="pearson")

    #se guardan en un arreglo todos los valores obtenidos
    resultados.append([variable_x, variable_y, r, abs(r)])

# el arreglo de resultados se transforman en df de pandas para manipularlo
# Convertir los resultados en un DataFrame
df_resultados = pd.DataFrame( 
    resultados,
    columns=["Variable X",
             "Variable Y",
             "Pearson",
             "Intensidad"] # es el valor absoluto de r
)

# Ordenar por intensidad de mayor a menor
df_resultados = df_resultados.sort_values(
    by="Intensidad", # esta es la variable por el cual se ordena
    ascending=False # aplicamos un ordenamiento ascendente
).reset_index(drop=True) #drop=True evita que el indice original se agregue como 

display(df_resultados)

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6                    gdp       life_expectancy  0.675566    0.675566
7      percentage_health       life_expectancy  0.286925    0.286925
8      percentage_health                   gdp  0.193442    0.193442
9   child_deaths_under_5       life_expectancy -0.067931    0.067931
10  child_deaths_under_5                   gdp -0.062524    0.062524
11  child_deaths_under_5     percentage_health -0.049833    0.049833
12                births                   gdp -0.044742    0.044742
13                births     percentage_health -0.030696    0.030696
14            population                   gdp -0.030289    0.030289
15                deaths                   gdp -0.028315    0.028315
16                births       life_expectancy -0.019662    0.019662
17            population     percentage_health -0.016296    0.016296
18                deaths     percentage_health -0.012450    0.012450
19            population       life_expectancy  0.006890    0.006890
20                deaths       life_expectancy -0.001312    0.001312